const std = @import("std");

pub const live_dashboard_stream_schema = "zigeffect.causal.live-dashboard-stream.v1";
pub const live_dashboard_stream_schema_version: u32 = 1;
pub const live_dashboard_report_schema = "zigeffect.causal.live-dashboard-streaming-workbench.v1";
pub const live_dashboard_report_schema_version: u32 = 1;

const OutputFormat = enum { text, json };
const generated_by = "causal-live-dashboard-streaming-workbench";
const solid_adapter = "@dschz/solid-g6";
const graph_engine = "@antv/g6";
const direct_engine_api = "not-required";
const recommended_next_branch = "codex/zigeffect-causal-workbench-graph-visual-debugging";

const source_contracts: []const []const u8 = &.{
    "zigeffect.causal.production-artifact-aggregation.v1",
    "zigeffect.causal.durable-production-retention.v1",
    "zigeffect.causal.artifact-access-control.v1",
    "zigeffect.causal.unified-spine-contract.v1",
    "zigeffect.causal.alerting-integrations.v1",
};

const deliverables: []const []const u8 = &.{
    "streaming artifact protocol",
    "read-only dashboard view",
    "bounded live-update fixture",
    "Solid G6 graph adapter boundary",
    "Visual Graph tab backed by the causal graph model",
    "dagre force and radial layout fixture",
    "SolidJS workbench verification",
};

const frame_fields: []const []const u8 = &.{
    "sequence",
    "event_id",
    "parent_id",
    "event_kind",
    "status",
    "label",
    "lane",
    "finding_kind",
    "dashboard_priority",
};

const layout_modes: []const []const u8 = &.{ "dagre", "force", "radial" };
const priority_levels: []const []const u8 = &.{ "normal", "watch", "critical" };

const adapter_contract: []const []const u8 = &.{
    "SolidJS adapter imports @dschz/solid-g6",
    "AntV G6 remains the graph engine dependency",
    "causal graph model remains source of truth",
    "direct @antv/g6 engine API remains not-required for this slice",
    "fallback evidence list remains visible if canvas initialization fails",
};

const guardrails: []const []const u8 = &.{
    "read-only dashboard evidence only",
    "mutation authority remains none",
    "stream frames are bounded local evidence",
    "no commands are executed from the UI",
    "redaction state is displayed but raw payload recovery is not attempted",
};

const non_goals: []const []const u8 = &.{
    "production telemetry ingestion",
    "SSE WebSocket polling or bridge callback transport",
    "Cockroach adapter work",
    "React workbench support",
    "RBAC enforcement",
    "source config registry policy migration deployment rollback alert ticket SIEM page or durable-store mutation",
};

const verification_commands: []const []const u8 = &.{
    "cd packages/zigeffect",
    "zig test tools/causal_live_dashboard_streaming_workbench.zig",
    "zig build causal-live-dashboard-streaming-workbench",
    "zig build causal-live-dashboard-streaming-workbench -- --format json",
    "zig build causal-schema-governance -- --format json",
    "zig build causal-production-hardening-backlog -- --format json",
    "zig build examples",
    "zig build test",
    "cd ../..",
    "bun run zigeffect:workbench:test",
    "bun run zigeffect:workbench:typecheck",
    "bun run zigeffect:workbench:build",
    "bun run check",
    "bun run zig:test",
    "git diff --check",
};

fn usage() []const u8 {
    return
        \\usage:
        \\  zig build causal-live-dashboard-streaming-workbench
        \\  zig build causal-live-dashboard-streaming-workbench -- --format text
        \\  zig build causal-live-dashboard-streaming-workbench -- --format json
        \\
        \\formats:
        \\  --format text|json
        \\
    ;
}

fn parseOptions(args: []const []const u8) !OutputFormat {
    if (args.len == 1) return .text;
    if (args.len == 3 and std.mem.eql(u8, args[1], "--format")) {
        if (std.mem.eql(u8, args[2], "text")) return .text;
        if (std.mem.eql(u8, args[2], "json")) return .json;
        return error.UnknownFormat;
    }
    if (args.len == 2 and std.mem.eql(u8, args[1], "--format")) return error.MissingFormat;
    return error.UnknownFlag;
}

pub fn formatLiveDashboardStreamingWorkbenchText(allocator: std.mem.Allocator) ![]const u8 {
    var output = std.ArrayList(u8).empty;
    errdefer output.deinit(allocator);

    try output.appendSlice(allocator, "zigeffect causal live dashboard streaming workbench\n");
    try output.print(allocator, "schema: {s}\n", .{live_dashboard_report_schema});
    try output.print(allocator, "schema_version: {d}\n", .{live_dashboard_report_schema_version});
    try output.print(allocator, "stream schema: {s}\n", .{live_dashboard_stream_schema});
    try output.print(allocator, "stream schema_version: {d}\n", .{live_dashboard_stream_schema_version});
    try output.print(allocator, "generated by: {s}\n", .{generated_by});
    try output.print(allocator, "solid adapter: {s}\n", .{solid_adapter});
    try output.print(allocator, "graph engine: {s}\n", .{graph_engine});
    try output.print(allocator, "direct engine api: {s}\n", .{direct_engine_api});
    try output.print(allocator, "recommended next branch: {s}\n\n", .{recommended_next_branch});

    try appendTextList(allocator, &output, "source contracts", source_contracts);
    try appendTextList(allocator, &output, "deliverables", deliverables);
    try appendTextList(allocator, &output, "frame fields", frame_fields);
    try appendTextList(allocator, &output, "layout modes", layout_modes);
    try appendTextList(allocator, &output, "priority levels", priority_levels);
    try appendTextList(allocator, &output, "adapter contract", adapter_contract);
    try appendTextList(allocator, &output, "guardrails", guardrails);
    try appendTextList(allocator, &output, "non-goals", non_goals);
    try appendTextList(allocator, &output, "verification commands", verification_commands);

    return output.toOwnedSlice(allocator);
}

pub fn formatLiveDashboardStreamingWorkbenchJson(allocator: std.mem.Allocator) ![]const u8 {
    var output = std.ArrayList(u8).empty;
    errdefer output.deinit(allocator);

    try output.appendSlice(allocator, "{\n");
    try appendJsonStringProperty(allocator, &output, "schema", live_dashboard_report_schema, true);
    try appendJsonU32Property(allocator, &output, "schema_version", live_dashboard_report_schema_version, true);
    try appendJsonStringProperty(allocator, &output, "stream_schema", live_dashboard_stream_schema, true);
    try appendJsonU32Property(allocator, &output, "stream_schema_version", live_dashboard_stream_schema_version, true);
    try appendJsonStringProperty(allocator, &output, "generated_by", generated_by, true);
    try appendJsonStringProperty(allocator, &output, "solid_adapter", solid_adapter, true);
    try appendJsonStringProperty(allocator, &output, "graph_engine", graph_engine, true);
    try appendJsonStringProperty(allocator, &output, "direct_engine_api", direct_engine_api, true);
    try appendJsonStringProperty(allocator, &output, "recommended_next_branch", recommended_next_branch, true);
    try appendJsonStringArrayProperty(allocator, &output, "source_contracts", source_contracts, true);
    try appendJsonStringArrayProperty(allocator, &output, "deliverables", deliverables, true);
    try appendJsonStringArrayProperty(allocator, &output, "frame_fields", frame_fields, true);
    try appendJsonStringArrayProperty(allocator, &output, "layout_modes", layout_modes, true);
    try appendJsonStringArrayProperty(allocator, &output, "priority_levels", priority_levels, true);
    try appendJsonStringArrayProperty(allocator, &output, "adapter_contract", adapter_contract, true);
    try appendJsonStringArrayProperty(allocator, &output, "guardrails", guardrails, true);
    try appendJsonStringArrayProperty(allocator, &output, "non_goals", non_goals, true);
    try appendJsonStringArrayProperty(allocator, &output, "verification_commands", verification_commands, false);
    try output.appendSlice(allocator, "}\n");

    return output.toOwnedSlice(allocator);
}

fn appendTextList(
    allocator: std.mem.Allocator,
    output: *std.ArrayList(u8),
    heading: []const u8,
    values: []const []const u8,
) !void {
    try output.print(allocator, "{s}:\n", .{heading});
    for (values) |value| {
        try output.print(allocator, "- {s}\n", .{value});
    }
    try output.append(allocator, '\n');
}

fn appendJsonStringProperty(
    allocator: std.mem.Allocator,
    output: *std.ArrayList(u8),
    name: []const u8,
    value: []const u8,
    trailing: bool,
) std.mem.Allocator.Error!void {
    try output.appendSlice(allocator, "  \"");
    try output.appendSlice(allocator, name);
    try output.appendSlice(allocator, "\": ");
    try appendJsonString(allocator, output, value);
    try output.appendSlice(allocator, if (trailing) ",\n" else "\n");
}

fn appendJsonU32Property(
    allocator: std.mem.Allocator,
    output: *std.ArrayList(u8),
    name: []const u8,
    value: u32,
    trailing: bool,
) std.mem.Allocator.Error!void {
    try output.print(allocator, "  \"{s}\": {d}", .{ name, value });
    try output.appendSlice(allocator, if (trailing) ",\n" else "\n");
}

fn appendJsonStringArrayProperty(
    allocator: std.mem.Allocator,
    output: *std.ArrayList(u8),
    name: []const u8,
    values: []const []const u8,
    trailing: bool,
) std.mem.Allocator.Error!void {
    try output.print(allocator, "  \"{s}\": [", .{name});
    for (values, 0..) |value, index| {
        if (index > 0) try output.appendSlice(allocator, ", ");
        try appendJsonString(allocator, output, value);
    }
    try output.appendSlice(allocator, if (trailing) "],\n" else "]\n");
}

fn appendJsonString(
    allocator: std.mem.Allocator,
    output: *std.ArrayList(u8),
    value: []const u8,
) std.mem.Allocator.Error!void {
    try output.append(allocator, '"');
    for (value) |byte| {
        switch (byte) {
            '"' => try output.appendSlice(allocator, "\\\""),
            '\\' => try output.appendSlice(allocator, "\\\\"),
            '\n' => try output.appendSlice(allocator, "\\n"),
            '\r' => try output.appendSlice(allocator, "\\r"),
            '\t' => try output.appendSlice(allocator, "\\t"),
            else => try output.append(allocator, byte),
        }
    }
    try output.append(allocator, '"');
}

fn failUsage(err: anyerror) noreturn {
    std.debug.print("causal-live-dashboard-streaming-workbench error: {s}\n{s}", .{ @errorName(err), usage() });
    std.process.exit(1);
}

pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    const format = parseOptions(args) catch |err| failUsage(err);
    const report = switch (format) {
        .text => try formatLiveDashboardStreamingWorkbenchText(init.gpa),
        .json => try formatLiveDashboardStreamingWorkbenchJson(init.gpa),
    };
    defer init.gpa.free(report);

    std.debug.print("{s}", .{report});
}

fn expectString(values: []const []const u8, expected: []const u8) !void {
    for (values) |value| {
        if (std.mem.eql(u8, value, expected)) return;
    }
    return error.MissingExpectedString;
}

test "live dashboard metadata preserves source contracts layouts and next branch" {
    try std.testing.expectEqualStrings("zigeffect.causal.live-dashboard-stream.v1", live_dashboard_stream_schema);
    try std.testing.expectEqual(@as(u32, 1), live_dashboard_stream_schema_version);
    try std.testing.expectEqualStrings("@dschz/solid-g6", solid_adapter);
    try std.testing.expectEqualStrings("@antv/g6", graph_engine);
    try std.testing.expectEqualStrings("not-required", direct_engine_api);
    try std.testing.expectEqualStrings("codex/zigeffect-causal-workbench-graph-visual-debugging", recommended_next_branch);
    try expectString(source_contracts, "zigeffect.causal.production-artifact-aggregation.v1");
    try expectString(source_contracts, "zigeffect.causal.artifact-access-control.v1");
    try expectString(source_contracts, "zigeffect.causal.unified-spine-contract.v1");
    try expectString(layout_modes, "dagre");
    try expectString(layout_modes, "force");
    try expectString(layout_modes, "radial");
}

test "live dashboard report preserves frame fields deliverables guardrails and non-goals" {
    try expectString(deliverables, "streaming artifact protocol");
    try expectString(deliverables, "read-only dashboard view");
    try expectString(deliverables, "bounded live-update fixture");
    try expectString(deliverables, "Solid G6 graph adapter boundary");
    try expectString(deliverables, "Visual Graph tab backed by the causal graph model");
    try expectString(frame_fields, "sequence");
    try expectString(frame_fields, "dashboard_priority");
    try expectString(priority_levels, "critical");
    try expectString(guardrails, "mutation authority remains none");
    try expectString(non_goals, "production telemetry ingestion");
    try expectString(non_goals, "Cockroach adapter work");
    try expectString(non_goals, "React workbench support");
}

test "live dashboard report parses output format options" {
    try std.testing.expectEqual(OutputFormat.text, try parseOptions(&.{"zigeffect-causal-live-dashboard-streaming-workbench"}));
    try std.testing.expectEqual(OutputFormat.text, try parseOptions(&.{ "zigeffect-causal-live-dashboard-streaming-workbench", "--format", "text" }));
    try std.testing.expectEqual(OutputFormat.json, try parseOptions(&.{ "zigeffect-causal-live-dashboard-streaming-workbench", "--format", "json" }));
    try std.testing.expectError(error.UnknownFlag, parseOptions(&.{ "zigeffect-causal-live-dashboard-streaming-workbench", "--json" }));
    try std.testing.expectError(error.MissingFormat, parseOptions(&.{ "zigeffect-causal-live-dashboard-streaming-workbench", "--format" }));
    try std.testing.expectError(error.UnknownFormat, parseOptions(&.{ "zigeffect-causal-live-dashboard-streaming-workbench", "--format", "xml" }));
}

test "live dashboard report names schema and hard boundaries" {
    const report = try formatLiveDashboardStreamingWorkbenchText(std.testing.allocator);
    defer std.testing.allocator.free(report);

    try std.testing.expect(std.mem.indexOf(u8, report, live_dashboard_stream_schema) != null);
    try std.testing.expect(std.mem.indexOf(u8, report, "@dschz/solid-g6") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, "production telemetry ingestion") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, "mutation authority remains none") != null);
}

test "live dashboard json report is machine readable" {
    const report = try formatLiveDashboardStreamingWorkbenchJson(std.testing.allocator);
    defer std.testing.allocator.free(report);

    try std.testing.expect(std.mem.indexOf(u8, report, "\"schema\": \"zigeffect.causal.live-dashboard-streaming-workbench.v1\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, "\"stream_schema\": \"zigeffect.causal.live-dashboard-stream.v1\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, "\"solid_adapter\": \"@dschz/solid-g6\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, "\"direct_engine_api\": \"not-required\"") != null);
}
