const std = @import("std");
const Capability = @import("../capability/root.zig");
const Stream = @import("../stream/root.zig");
const fx = @import("zigeffect");
const Boundary = @import("../boundary/root.zig");
const External = @import("../external/root.zig");

pub const deterministic_capability = Capability.Descriptor{ .id = "zigeffect-std.object-storage.memory", .kind = .object_storage, .maturity = .deterministic_model, .package = "zigeffect-std", .version = "0.1.0", .features = &.{ "put", "get", "head", "delete", "list", "multipart", "sha256", "stream-contract" }, .side_effects = .modeled };
pub const Metadata = struct { key: []const u8, size: usize, sha256: [32]u8, content_type: ?[]const u8 = null, version: u64 };
pub const Object = struct { allocator: std.mem.Allocator, metadata: Metadata, bytes: []u8, pub fn deinit(self: *Object) void { self.allocator.free(self.metadata.key); if (self.metadata.content_type) |value| self.allocator.free(value); self.allocator.free(self.bytes); self.* = undefined; } };
pub fn objectBodyStreamAlloc(allocator: std.mem.Allocator, object: *const Object) !fx.EffectStream(u8, anyerror, Stream.EmptyEnv) { return Stream.ownedBytesAlloc(allocator, object.bytes); }
pub const PutOptions = struct { content_type: ?[]const u8 = null, expected_sha256: ?[32]u8 = null, only_if_absent: bool = false };
pub const Part = struct { number: u32, bytes: []const u8, sha256: [32]u8 };
pub const Multipart = struct { upload_id: u64, key: []const u8 };
pub const ListResult = struct { allocator: std.mem.Allocator, keys: [][]u8, pub fn deinit(self: *ListResult) void { for (self.keys) |key| self.allocator.free(key); self.allocator.free(self.keys); self.* = undefined; } };
pub const Service = struct {
    pointer: *anyopaque,
    put_fn: *const fn (*anyopaque, []const u8, []const u8, PutOptions) anyerror!Metadata,
    get_fn: *const fn (*anyopaque, std.mem.Allocator, []const u8) anyerror!?Object,
    head_fn: *const fn (*anyopaque, []const u8) anyerror!?Metadata,
    delete_fn: *const fn (*anyopaque, []const u8) anyerror!bool,
    list_fn: *const fn (*anyopaque, std.mem.Allocator, []const u8, usize) anyerror!ListResult,
    begin_fn: *const fn (*anyopaque, []const u8) anyerror!Multipart,
    part_fn: *const fn (*anyopaque, u64, Part) anyerror!void,
    complete_fn: *const fn (*anyopaque, u64, PutOptions) anyerror!Metadata,
    observer: ?Boundary.Observer = null,
    pub fn from(comptime T: type, pointer: *T) Service { return .{ .pointer = pointer, .put_fn = struct { fn call(raw: *anyopaque, key: []const u8, bytes: []const u8, options: PutOptions) anyerror!Metadata { return (@as(*T, @ptrCast(@alignCast(raw)))).put(key, bytes, options); } }.call, .get_fn = struct { fn call(raw: *anyopaque, allocator: std.mem.Allocator, key: []const u8) anyerror!?Object { return (@as(*T, @ptrCast(@alignCast(raw)))).getAlloc(allocator, key); } }.call, .head_fn = struct { fn call(raw: *anyopaque, key: []const u8) anyerror!?Metadata { return (@as(*T, @ptrCast(@alignCast(raw)))).head(key); } }.call, .delete_fn = struct { fn call(raw: *anyopaque, key: []const u8) anyerror!bool { return (@as(*T, @ptrCast(@alignCast(raw)))).delete(key); } }.call, .list_fn = struct { fn call(raw: *anyopaque, allocator: std.mem.Allocator, prefix: []const u8, limit: usize) anyerror!ListResult { return (@as(*T, @ptrCast(@alignCast(raw)))).listAlloc(allocator, prefix, limit); } }.call, .begin_fn = struct { fn call(raw: *anyopaque, key: []const u8) anyerror!Multipart { return (@as(*T, @ptrCast(@alignCast(raw)))).beginMultipart(key); } }.call, .part_fn = struct { fn call(raw: *anyopaque, id: u64, part: Part) anyerror!void { return (@as(*T, @ptrCast(@alignCast(raw)))).uploadPart(id, part); } }.call, .complete_fn = struct { fn call(raw: *anyopaque, id: u64, options: PutOptions) anyerror!Metadata { return (@as(*T, @ptrCast(@alignCast(raw)))).completeMultipart(id, options); } }.call }; }
    pub fn observed(self: Service, observer: Boundary.Observer) Service { var result = self; result.observer = observer; return result; }
    pub fn put(self: Service, key: []const u8, bytes: []const u8, options: PutOptions) !Metadata { self.emit("put", .started, key, null); const result = self.put_fn(self.pointer, key, bytes, options) catch |err| { self.emit("put", .failed, key, External.classifyError(err)); return err; }; self.emit("put", .succeeded, key, null); return result; }
    pub fn getAlloc(self: Service, allocator: std.mem.Allocator, key: []const u8) !?Object { self.emit("get", .started, key, null); const result = self.get_fn(self.pointer, allocator, key) catch |err| { self.emit("get", .failed, key, External.classifyError(err)); return err; }; self.emit("get", .succeeded, key, null); return result; }
    pub fn listAlloc(self: Service, allocator: std.mem.Allocator, prefix: []const u8, limit: usize) !ListResult { const result = self.list_fn(self.pointer, allocator, prefix, limit) catch |err| { self.emit("list", .failed, prefix, External.classifyError(err)); return err; }; self.emit("list", .succeeded, prefix, null); return result; }
    pub fn beginMultipart(self: Service, key: []const u8) !Multipart { const result = self.begin_fn(self.pointer, key) catch |err| { self.emit("multipart-begin", .failed, key, External.classifyError(err)); return err; }; self.emit("multipart-begin", .succeeded, key, null); return result; }
    pub fn uploadPart(self: Service, id: u64, part: Part) !void { self.part_fn(self.pointer, id, part) catch |err| { self.emit("multipart-part", .failed, "", External.classifyError(err)); return err; }; self.emit("multipart-part", .succeeded, "", null); }
    pub fn completeMultipart(self: Service, id: u64, options: PutOptions) !Metadata { const result = self.complete_fn(self.pointer, id, options) catch |err| { self.emit("multipart-complete", .failed, "", External.classifyError(err)); return err; }; self.emit("multipart-complete", .succeeded, result.key, null); return result; }
    fn emit(self: Service, operation: []const u8, status: Boundary.Status, key: []const u8, class: ?External.Class) void { if (self.observer) |observer| observer.emit(.object_storage, operation, status, key, class); }
};
const Stored = struct { bytes: []u8, content_type: ?[]u8, digest: [32]u8, version: u64 };
const StoredPart = struct { number: u32, bytes: []u8, digest: [32]u8 };
const Upload = struct { key: []u8, parts: std.ArrayList(StoredPart) = .empty };
pub const Memory = struct {
    allocator: std.mem.Allocator,
    objects: std.StringHashMap(Stored),
    uploads: std.AutoHashMap(u64, Upload),
    next_upload_id: u64 = 1,
    mutex: std.atomic.Mutex = .unlocked,
    pub fn init(allocator: std.mem.Allocator) Memory { return .{ .allocator = allocator, .objects = .init(allocator), .uploads = .init(allocator) }; }
    pub fn deinit(self: *Memory) void { var objects = self.objects.iterator(); while (objects.next()) |entry| { self.allocator.free(entry.key_ptr.*); self.freeStored(entry.value_ptr.*); } self.objects.deinit(); var uploads = self.uploads.valueIterator(); while (uploads.next()) |upload| self.freeUpload(upload.*); self.uploads.deinit(); }
    pub fn asService(self: *Memory) Service { return Service.from(Memory, self); }
    pub fn put(self: *Memory, key: []const u8, bytes: []const u8, options: PutOptions) !Metadata { try validateKey(key); if (bytes.len > 128 * 1024 * 1024) return error.ObjectTooLarge; const digest = sha256(bytes); if (options.expected_sha256) |expected| if (!std.crypto.timing_safe.eql([32]u8, expected, digest)) return error.ChecksumMismatch; self.lock(); defer self.mutex.unlock(); if (options.only_if_absent and self.objects.contains(key)) return error.ObjectAlreadyExists; const next = if (self.objects.get(key)) |existing| existing.version + 1 else 1; if (self.objects.fetchRemove(key)) |old| { self.allocator.free(old.key); self.freeStored(old.value); } const owned_key = try self.allocator.dupe(u8, key); errdefer self.allocator.free(owned_key); const owned_bytes = try self.allocator.dupe(u8, bytes); errdefer self.allocator.free(owned_bytes); const content_type = if (options.content_type) |value| try self.allocator.dupe(u8, value) else null; errdefer if (content_type) |value| self.allocator.free(value); try self.objects.put(owned_key, .{ .bytes = owned_bytes, .content_type = content_type, .digest = digest, .version = next }); return .{ .key = key, .size = bytes.len, .sha256 = digest, .content_type = options.content_type, .version = next }; }
    pub fn getAlloc(self: *Memory, allocator: std.mem.Allocator, key: []const u8) !?Object { try validateKey(key); self.lock(); defer self.mutex.unlock(); const stored = self.objects.get(key) orelse return null; const owned_key = try allocator.dupe(u8, key); errdefer allocator.free(owned_key); const bytes = try allocator.dupe(u8, stored.bytes); errdefer allocator.free(bytes); const content_type = if (stored.content_type) |value| try allocator.dupe(u8, value) else null; return .{ .allocator = allocator, .metadata = .{ .key = owned_key, .size = bytes.len, .sha256 = stored.digest, .content_type = content_type, .version = stored.version }, .bytes = bytes }; }
    pub fn head(self: *Memory, key: []const u8) !?Metadata { try validateKey(key); self.lock(); defer self.mutex.unlock(); const stored = self.objects.get(key) orelse return null; return .{ .key = key, .size = stored.bytes.len, .sha256 = stored.digest, .content_type = stored.content_type, .version = stored.version }; }
    pub fn delete(self: *Memory, key: []const u8) !bool { try validateKey(key); self.lock(); defer self.mutex.unlock(); const old = self.objects.fetchRemove(key) orelse return false; self.allocator.free(old.key); self.freeStored(old.value); return true; }
    pub fn listAlloc(self: *Memory, allocator: std.mem.Allocator, prefix: []const u8, limit: usize) !ListResult { if (limit == 0 or limit > 10_000) return error.InvalidListLimit; self.lock(); defer self.mutex.unlock(); var result = std.ArrayList([]u8).empty; errdefer { for (result.items) |key| allocator.free(key); result.deinit(allocator); } var iterator = self.objects.keyIterator(); while (iterator.next()) |key| { if (!std.mem.startsWith(u8, key.*, prefix)) continue; try result.append(allocator, try allocator.dupe(u8, key.*)); if (result.items.len == limit) break; } std.mem.sort([]u8, result.items, {}, struct { fn less(_: void, left: []u8, right: []u8) bool { return std.mem.lessThan(u8, left, right); } }.less); return .{ .allocator = allocator, .keys = try result.toOwnedSlice(allocator) }; }
    pub fn beginMultipart(self: *Memory, key: []const u8) !Multipart { try validateKey(key); self.lock(); defer self.mutex.unlock(); const id = self.next_upload_id; self.next_upload_id += 1; const owned = try self.allocator.dupe(u8, key); errdefer self.allocator.free(owned); try self.uploads.put(id, .{ .key = owned }); return .{ .upload_id = id, .key = key }; }
    pub fn uploadPart(self: *Memory, id: u64, part: Part) !void { if (part.number == 0 or part.bytes.len == 0 or part.bytes.len > 16 * 1024 * 1024 or !std.crypto.timing_safe.eql([32]u8, part.sha256, sha256(part.bytes))) return error.InvalidMultipartPart; self.lock(); defer self.mutex.unlock(); const upload = self.uploads.getPtr(id) orelse return error.UploadNotFound; for (upload.parts.items) |stored| if (stored.number == part.number) return error.DuplicatePart; const bytes = try self.allocator.dupe(u8, part.bytes); errdefer self.allocator.free(bytes); try upload.parts.append(self.allocator, .{ .number = part.number, .bytes = bytes, .digest = part.sha256 }); }
    pub fn completeMultipart(self: *Memory, id: u64, options: PutOptions) !Metadata { self.lock(); const removed = self.uploads.fetchRemove(id) orelse { self.mutex.unlock(); return error.UploadNotFound; }; const upload = removed.value; self.mutex.unlock(); defer self.freeUpload(upload); std.mem.sort(StoredPart, upload.parts.items, {}, struct { fn less(_: void, left: StoredPart, right: StoredPart) bool { return left.number < right.number; } }.less); var total: usize = 0; for (upload.parts.items, 0..) |part, index| { if (part.number != index + 1) return error.MissingMultipartPart; total += part.bytes.len; } const joined = try self.allocator.alloc(u8, total); defer self.allocator.free(joined); var offset: usize = 0; for (upload.parts.items) |part| { @memcpy(joined[offset .. offset + part.bytes.len], part.bytes); offset += part.bytes.len; } return self.put(upload.key, joined, options); }
    fn freeStored(self: *Memory, stored: Stored) void { self.allocator.free(stored.bytes); if (stored.content_type) |value| self.allocator.free(value); }
    fn freeUpload(self: *Memory, upload: Upload) void { self.allocator.free(upload.key); for (upload.parts.items) |part| self.allocator.free(part.bytes); var parts = upload.parts; parts.deinit(self.allocator); }
    fn lock(self: *Memory) void { while (!self.mutex.tryLock()) std.Thread.yield() catch {}; }
};
fn validateKey(key: []const u8) !void { if (key.len == 0 or key.len > 1024 or key[0] == '/' or std.mem.indexOf(u8, key, "..") != null) return error.InvalidObjectKey; }
pub fn sha256(bytes: []const u8) [32]u8 { var digest: [32]u8 = undefined; std.crypto.hash.sha2.Sha256.hash(bytes, &digest, .{}); return digest; }
pub fn conform(service: Service, allocator: std.mem.Allocator) !void { const digest = sha256("hello"); const metadata = try service.put("attachments/a.txt", "hello", .{ .expected_sha256 = digest, .content_type = "text/plain" }); try std.testing.expectEqual(@as(usize, 5), metadata.size); var object = (try service.getAlloc(allocator, "attachments/a.txt")).?; defer object.deinit(); try std.testing.expectEqualStrings("hello", object.bytes); const upload = try service.beginMultipart("attachments/b.txt"); const first_part = try allocator.alloc(u8, 5 * 1024 * 1024); defer allocator.free(first_part); @memset(first_part, 'a'); try service.uploadPart(upload.upload_id, .{ .number = 1, .bytes = first_part, .sha256 = sha256(first_part) }); try service.uploadPart(upload.upload_id, .{ .number = 2, .bytes = "two", .sha256 = sha256("two") }); _ = try service.completeMultipart(upload.upload_id, .{}); var combined = (try service.getAlloc(allocator, "attachments/b.txt")).?; defer combined.deinit(); try std.testing.expectEqual(first_part.len + 3, combined.bytes.len); try std.testing.expect(std.mem.endsWith(u8, combined.bytes, "two")); var listed = try service.listAlloc(allocator, "attachments/", 10); defer listed.deinit(); try std.testing.expectEqual(@as(usize, 2), listed.keys.len); }
test "deterministic object storage satisfies checksums list multipart and causal conformance" { var storage = Memory.init(std.testing.allocator); defer storage.deinit(); var evidence = Boundary.Recorder.init(std.testing.allocator); defer evidence.deinit(); try conform(storage.asService().observed(evidence.asObserver()), std.testing.allocator); try std.testing.expect(evidence.facts.items.len >= 10); try std.testing.expectError(error.ChecksumMismatch, storage.put("bad", "data", .{ .expected_sha256 = [_]u8{0} ** 32 })); }
