//! Effect ergonomics M1 — the small, daily-use combinators the EffectTS surface
//! exposes that this engine had not yet shipped. Each wrapper follows the same
//! Parent + run/exit structure as the existing MapEffect / TapEffect / etc., so
//! it composes naturally inside the existing pipeline.
//!
//! Milestones covered: M3.1 as / M3.2 replace / M3.3 asVoid / M3.4 andThen
//! (alias for flatMap; method on base Effect) / M3.8 when / M3.9 unless.

const std = @import("std");
const context_mod = @import("../core/context.zig");
const result_mod = @import("../core/result.zig");

pub const Allocator = std.mem.Allocator;
pub const Context = context_mod.Context;
pub const Exit = result_mod.Exit;

/// A side-by-side tuple of two effect successes. Generated by `zip`.
pub fn ZipPair(comptime Left: type, comptime Right: type) type {
    return struct { left: Left, right: Right };
}

// Forward-declared wrappers that AsEffect / WhenEffect chain into. The full
// `effect.zig` imports this module and references `AsEffect` / `WhenEffect`;
// `MapEffect` / `FlatMapEffect` are defined in `effect.zig` and looked up
// lazily via `@import` inside the methods (no cycle: `effect.zig` does NOT
// re-import this module from inside the chained methods).
const effect_mod = @import("effect.zig");

/// Runs the parent for its side effect, discards its success, returns a stored
/// constant. Implements `as` / `replace` (`asVoid` is the void specialization).
pub fn AsEffect(comptime Parent: type, comptime NewSuccess: type, comptime Env: type) type {
    return struct {
        const Self = @This();
        pub const SuccessType = NewSuccess;
        pub const FailureType = Parent.FailureType;
        pub const EnvType = Env;

        parent: Parent,
        replacement: NewSuccess,

        pub fn run(self: Self, ctx: *Context(Env)) Parent.FailureType!NewSuccess {
            _ = try ctx.runEffect(self.parent);
            return self.replacement;
        }

        pub fn exit(self: Self, ctx: *Context(Env)) Exit(NewSuccess, Parent.FailureType) {
            const parent_exit = ctx.exitEffect(self.parent);
            return switch (parent_exit) {
                .success => .{ .success = self.replacement },
                .failure => |err| .{ .failure = err },
                .interrupted => .interrupted,
                .defect => |msg| .{ .defect = msg },
            };
        }

        // Chainable into the existing pipeline — matches the convention of
        // every other Effect wrapper (TapEffect, OnExitEffect, etc.).
        pub fn map(
            self: Self,
            comptime Next: type,
            mapper: *const fn (NewSuccess) Next,
        ) effect_mod.MapEffect(Self, Next, Parent.FailureType, Env) {
            return .{ .parent = self, .mapper = mapper };
        }

        pub fn flatMap(
            self: Self,
            comptime Next: type,
            binder: *const fn (NewSuccess, *Context(Env)) Parent.FailureType!Next,
        ) effect_mod.FlatMapEffect(Self, Next, Parent.FailureType, Env) {
            return .{ .parent = self, .binder = binder };
        }
    };
}

/// Runs the parent only if `cond` is true; returns `?Success` (null when skipped).
/// `unless` is the inverse, implemented as `WhenEffect` with the condition flipped
/// at the factory site.
pub fn WhenEffect(comptime Parent: type, comptime Env: type) type {
    return struct {
        const Self = @This();
        pub const SuccessType = ?Parent.SuccessType;
        pub const FailureType = Parent.FailureType;
        pub const EnvType = Env;

        parent: Parent,
        cond: bool,

        pub fn run(self: Self, ctx: *Context(Env)) Parent.FailureType!?Parent.SuccessType {
            if (!self.cond) return null;
            const value = try ctx.runEffect(self.parent);
            return value;
        }

        pub fn exit(self: Self, ctx: *Context(Env)) Exit(?Parent.SuccessType, Parent.FailureType) {
            if (!self.cond) return .{ .success = null };
            const parent_exit = ctx.exitEffect(self.parent);
            return switch (parent_exit) {
                .success => |value| .{ .success = value },
                .failure => |err| .{ .failure = err },
                .interrupted => .interrupted,
                .defect => |msg| .{ .defect = msg },
            };
        }

        pub fn map(
            self: Self,
            comptime Next: type,
            mapper: *const fn (?Parent.SuccessType) Next,
        ) effect_mod.MapEffect(Self, Next, Parent.FailureType, Env) {
            return .{ .parent = self, .mapper = mapper };
        }

        pub fn flatMap(
            self: Self,
            comptime Next: type,
            binder: *const fn (?Parent.SuccessType, *Context(Env)) Parent.FailureType!Next,
        ) effect_mod.FlatMapEffect(Self, Next, Parent.FailureType, Env) {
            return .{ .parent = self, .binder = binder };
        }
    };
}

// ─── Sequential combinators (M3.5–M3.7, M3.10–M3.11) ─────────────────────────

/// Sequential pair — run left, then right, return both successes. Failure
/// short-circuits at left; right does not run if left failed.
pub fn ZipEffect(
    comptime Left: type,
    comptime Right: type,
    comptime Failure: type,
    comptime Env: type,
) type {
    return struct {
        const Self = @This();
        pub const SuccessType = ZipPair(Left.SuccessType, Right.SuccessType);
        pub const FailureType = Failure;
        pub const EnvType = Env;

        left: Left,
        right: Right,

        pub fn run(self: Self, ctx: *Context(Env)) Failure!SuccessType {
            const a = try ctx.runEffect(self.left);
            const b = try ctx.runEffect(self.right);
            return .{ .left = a, .right = b };
        }

        pub fn exit(self: Self, ctx: *Context(Env)) Exit(SuccessType, Failure) {
            const value = ctx.runEffect(self) catch |err| return .{ .failure = err };
            return .{ .success = value };
        }

        pub fn map(
            self: Self,
            comptime Next: type,
            mapper: *const fn (SuccessType) Next,
        ) effect_mod.MapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .mapper = mapper };
        }

        pub fn flatMap(
            self: Self,
            comptime Next: type,
            binder: *const fn (SuccessType, *Context(Env)) Failure!Next,
        ) effect_mod.FlatMapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .binder = binder };
        }
    };
}

/// Sequential pair + combiner — like `ZipEffect` but applies `combine` to the
/// two successes. Failure short-circuits at left.
pub fn ZipWithEffect(
    comptime Left: type,
    comptime Right: type,
    comptime Combined: type,
    comptime Failure: type,
    comptime Env: type,
) type {
    return struct {
        const Self = @This();
        pub const SuccessType = Combined;
        pub const FailureType = Failure;
        pub const EnvType = Env;

        left: Left,
        right: Right,
        combine: *const fn (Left.SuccessType, Right.SuccessType) Combined,

        pub fn run(self: Self, ctx: *Context(Env)) Failure!Combined {
            const a = try ctx.runEffect(self.left);
            const b = try ctx.runEffect(self.right);
            return self.combine(a, b);
        }

        pub fn exit(self: Self, ctx: *Context(Env)) Exit(Combined, Failure) {
            const value = ctx.runEffect(self) catch |err| return .{ .failure = err };
            return .{ .success = value };
        }

        pub fn map(
            self: Self,
            comptime Next: type,
            mapper: *const fn (Combined) Next,
        ) effect_mod.MapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .mapper = mapper };
        }

        pub fn flatMap(
            self: Self,
            comptime Next: type,
            binder: *const fn (Combined, *Context(Env)) Failure!Next,
        ) effect_mod.FlatMapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .binder = binder };
        }
    };
}

// ─── Track 4 — Structured concurrency (M4.1 / M4.2) ──────────────────────────
//
// These primitives use `ctx.executor` (set via `Runtime(Env).withExecutor` /
// `FiberRuntime.withExecutor`, plumbed onto Context in M1.1) to spawn each
// branch as a real coroutine. When no executor is configured they fall back to
// the sequential traversal — same result, same causal trace structurally. The
// "same causal structure either way" invariant is the load-bearing claim of
// the deep integration; these primitives are the user-facing surface that
// dogfoods it.
//
// Threading contract: the configured executor may be single-executor cooperative
// (zio) or a real OS-thread executor. `CausalStore`, `Ref`, and `Hub` guard their
// write paths, but the per-job `Context` is still a shallow copy that may share
// host-provided services, scopes, and allocators. Those shared values must be
// thread-safe for OS-thread executors; read-side inspection still needs a
// quiescent barrier after all spawned jobs join.
//
// Failure semantics: the parallel family joins every spawned branch before it
// returns unless the primitive explicitly short-circuits via an executor
// `interrupt`/`waitAny` path (`race*` / `both`). This preserves structured
// cleanup and gives snapshots a quiescent point.
//
// Result-lifetime contract: per-item `Result` values that succeed are NOT
// freed by the primitive on partial failure. If `Result` owns heap
// allocations, the failing-path leaks them. v1 callers MUST use a non-owning
// `Result` type (POD value) OR wrap heap ownership in a parent `Scope` /
// allocator-arena that lives across the call. A future v2 may add a per-slot
// cleanup hook.

/// M4.1 — parallel traversal. Forks one fiber per item via the executor on
/// `ctx.executor`, then joins all to collect the result slice. With no executor
/// configured, falls back to a sequential traversal — same observable result.
pub fn ForEachParEffect(
    comptime Item: type,
    comptime Result: type,
    comptime Failure: type,
    comptime Env: type,
) type {
    return struct {
        const Self = @This();
        pub const SuccessType = []Result;
        pub const FailureType = Failure;
        pub const EnvType = Env;

        items: []const Item,
        body: *const fn (Item, *Context(Env)) Failure!Result,

        const JobCtx = struct {
            ctx_value: Context(Env),
            item: Item,
            body: *const fn (Item, *Context(Env)) Failure!Result,
            slot: *Slot,

            fn run(raw: ?*anyopaque) void {
                const self: *JobCtx = @ptrCast(@alignCast(raw.?));
                if (self.body(self.item, &self.ctx_value)) |value| {
                    self.slot.* = .{ .value = value };
                } else |err| {
                    self.slot.* = .{ .err = err };
                }
            }
        };

        const Slot = union(enum) {
            pending,
            value: Result,
            err: Failure,
        };

        pub fn run(self: Self, ctx: *Context(Env)) Failure!SuccessType {
            // Sequential fallback — no executor.
            if (ctx.executor == null) {
                const results = ctx.allocator.alloc(Result, self.items.len) catch return @as(Failure, error.OutOfMemory);
                errdefer ctx.allocator.free(results);
                for (self.items, 0..) |item, i| {
                    results[i] = try self.body(item, ctx);
                }
                return results;
            }

            const executor = ctx.executor.?;
            const results = ctx.allocator.alloc(Result, self.items.len) catch return @as(Failure, error.OutOfMemory);
            errdefer ctx.allocator.free(results);

            const slots = ctx.allocator.alloc(Slot, self.items.len) catch return @as(Failure, error.OutOfMemory);
            defer ctx.allocator.free(slots);
            for (slots) |*s| s.* = .pending;

            const jobs = ctx.allocator.alloc(JobCtx, self.items.len) catch return @as(Failure, error.OutOfMemory);
            defer ctx.allocator.free(jobs);

            const handles = ctx.allocator.alloc(?*anyopaque, self.items.len) catch return @as(Failure, error.OutOfMemory);
            defer ctx.allocator.free(handles);
            for (handles) |*h| h.* = null;

            // Spawn fibers, draining on first decline so inline-fallback bodies
            // never race with siblings already executing on the executor.
            for (self.items, 0..) |item, i| {
                jobs[i] = .{ .ctx_value = ctx.*, .item = item, .body = self.body, .slot = &slots[i] };
                handles[i] = executor.vtable.spawn(executor.context, .{ .context = &jobs[i], .run = JobCtx.run });
                if (handles[i] == null) {
                    // Spawn declined. Drain every prior in-flight handle BEFORE
                    // running anything inline on the parent stack, so the
                    // fallback can't race siblings on the shared `ctx` state.
                    for (handles[0..i]) |maybe_prior| {
                        if (maybe_prior) |h| {
                            executor.vtable.join(executor.context, h);
                            executor.vtable.destroy(executor.context, h);
                        }
                    }
                    // Run THIS item and every remaining one inline-sequential.
                    JobCtx.run(&jobs[i]);
                    var j = i + 1;
                    while (j < self.items.len) : (j += 1) {
                        jobs[j] = .{ .ctx_value = ctx.*, .item = self.items[j], .body = self.body, .slot = &slots[j] };
                        JobCtx.run(&jobs[j]);
                        handles[j] = null;
                    }
                    // Mark prior handles as already-joined for the join loop.
                    for (handles[0..i]) |*slot_h| slot_h.* = null;
                    break;
                }
            }

            // Await any handles still in flight. No early interrupt (M7.8).
            for (handles) |maybe_handle| {
                if (maybe_handle) |handle| {
                    executor.vtable.join(executor.context, handle);
                    executor.vtable.destroy(executor.context, handle);
                }
            }

            // Collect results / lowest-indexed failure (deterministic across
            // executors). A `.pending` slot here means the executor's `join`
            // contract was violated — surface a clear defect rather than UB.
            var first_err: ?Failure = null;
            for (slots, 0..) |slot, i| {
                switch (slot) {
                    .value => |v| results[i] = v,
                    .err => |e| if (first_err == null) {
                        first_err = e;
                    },
                    .pending => std.debug.panic(
                        "FiberExecutor.join contract violation: slot[{d}] still pending after join (see executor.zig VTable doc)",
                        .{i},
                    ),
                }
            }
            if (first_err) |e| return e;
            return results;
        }

        pub fn exit(self: Self, ctx: *Context(Env)) Exit(SuccessType, Failure) {
            const value = ctx.runEffect(self) catch |err| return .{ .failure = err };
            return .{ .success = value };
        }

        pub fn map(
            self: Self,
            comptime Next: type,
            mapper: *const fn (SuccessType) Next,
        ) effect_mod.MapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .mapper = mapper };
        }

        pub fn flatMap(
            self: Self,
            comptime Next: type,
            binder: *const fn (SuccessType, *Context(Env)) Failure!Next,
        ) effect_mod.FlatMapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .binder = binder };
        }
    };
}

/// M4.2 — parallel pair. Spawns both effects onto `ctx.executor` and awaits
/// both. With no executor, falls back to sequential (`zip`). Same result type
/// as `zip`: a `ZipPair{left, right}`.
pub fn ZipParEffect(
    comptime Left: type,
    comptime Right: type,
    comptime Failure: type,
    comptime Env: type,
) type {
    return struct {
        const Self = @This();
        pub const SuccessType = ZipPair(Left.SuccessType, Right.SuccessType);
        pub const FailureType = Failure;
        pub const EnvType = Env;

        left: Left,
        right: Right,

        const LeftSlot = union(enum) { pending, value: Left.SuccessType, err: Failure };
        const RightSlot = union(enum) { pending, value: Right.SuccessType, err: Failure };

        const LeftJob = struct {
            ctx_value: Context(Env),
            eff: Left,
            slot: *LeftSlot,
            fn run(raw: ?*anyopaque) void {
                const self: *LeftJob = @ptrCast(@alignCast(raw.?));
                if (self.ctx_value.runEffect(self.eff)) |v| {
                    self.slot.* = .{ .value = v };
                } else |err| {
                    self.slot.* = .{ .err = err };
                }
            }
        };
        const RightJob = struct {
            ctx_value: Context(Env),
            eff: Right,
            slot: *RightSlot,
            fn run(raw: ?*anyopaque) void {
                const self: *RightJob = @ptrCast(@alignCast(raw.?));
                if (self.ctx_value.runEffect(self.eff)) |v| {
                    self.slot.* = .{ .value = v };
                } else |err| {
                    self.slot.* = .{ .err = err };
                }
            }
        };

        pub fn run(self: Self, ctx: *Context(Env)) Failure!SuccessType {
            if (ctx.executor == null) {
                const a = try ctx.runEffect(self.left);
                const b = try ctx.runEffect(self.right);
                return .{ .left = a, .right = b };
            }
            const executor = ctx.executor.?;

            var ls: LeftSlot = .pending;
            var rs: RightSlot = .pending;
            var lj = LeftJob{ .ctx_value = ctx.*, .eff = self.left, .slot = &ls };
            var rj = RightJob{ .ctx_value = ctx.*, .eff = self.right, .slot = &rs };

            // Spawn left first. If it declines, don't bother spawning right —
            // run both inline-sequential so we never race the executor.
            const lh = executor.vtable.spawn(executor.context, .{ .context = &lj, .run = LeftJob.run });
            var rh: ?*anyopaque = null;
            if (lh == null) {
                LeftJob.run(&lj);
                RightJob.run(&rj);
            } else {
                rh = executor.vtable.spawn(executor.context, .{ .context = &rj, .run = RightJob.run });
                if (rh == null) {
                    // Right declined; drain left BEFORE running right inline
                    // so the inline body can't race left's in-flight fiber.
                    executor.vtable.join(executor.context, lh.?);
                    executor.vtable.destroy(executor.context, lh.?);
                    RightJob.run(&rj);
                } else {
                    executor.vtable.join(executor.context, lh.?);
                    executor.vtable.destroy(executor.context, lh.?);
                    executor.vtable.join(executor.context, rh.?);
                    executor.vtable.destroy(executor.context, rh.?);
                }
            }

            const left_val = switch (ls) {
                .value => |v| v,
                .err => |e| return e,
                .pending => std.debug.panic(
                    "FiberExecutor.join contract violation: left slot still pending after join",
                    .{},
                ),
            };
            const right_val = switch (rs) {
                .value => |v| v,
                .err => |e| return e,
                .pending => std.debug.panic(
                    "FiberExecutor.join contract violation: right slot still pending after join",
                    .{},
                ),
            };
            return .{ .left = left_val, .right = right_val };
        }

        pub fn exit(self: Self, ctx: *Context(Env)) Exit(SuccessType, Failure) {
            const value = ctx.runEffect(self) catch |err| return .{ .failure = err };
            return .{ .success = value };
        }

        pub fn map(
            self: Self,
            comptime Next: type,
            mapper: *const fn (SuccessType) Next,
        ) effect_mod.MapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .mapper = mapper };
        }

        pub fn flatMap(
            self: Self,
            comptime Next: type,
            binder: *const fn (SuccessType, *Context(Env)) Failure!Next,
        ) effect_mod.FlatMapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .binder = binder };
        }
    };
}

// ─── Race family (M4.3/M4.4/M4.5) ────────────────────────────────────────────
//
// These short-circuit via the executor's `waitAny` (M4.0) + `interrupt` (M7.8):
// spawn the branches, wait for the FIRST to complete, cancel the losers. When
// the executor can't race (no waitAny/interrupt, or no executor at all) they
// fall back to sequential evaluation of the first branch. Both branches must
// produce the same SuccessType.

fn raceSlotResult(comptime A: type, comptime Failure: type, slot: anytype) Failure!A {
    return switch (slot) {
        .value => |v| v,
        .err => |e| e,
        .pending => unreachable, // the winner completed before waitAny returned
    };
}

/// M4.4 — `raceFirst(left, right)`: the FIRST branch to complete (success OR
/// failure) wins; the loser is interrupted.
pub fn RaceFirstEffect(
    comptime Left: type,
    comptime Right: type,
    comptime Failure: type,
    comptime Env: type,
) type {
    return struct {
        const Self = @This();
        const A = Left.SuccessType;
        pub const SuccessType = A;
        pub const FailureType = Failure;
        pub const EnvType = Env;

        left: Left,
        right: Right,

        const Slot = union(enum) { pending, value: A, err: Failure };

        fn Job(comptime Eff: type) type {
            return struct {
                ctx_value: Context(Env),
                eff: Eff,
                slot: *Slot,
                fn run(raw: ?*anyopaque) void {
                    const self: *@This() = @ptrCast(@alignCast(raw.?));
                    if (self.ctx_value.runEffect(self.eff)) |v| {
                        self.slot.* = .{ .value = v };
                    } else |e| {
                        self.slot.* = .{ .err = e };
                    }
                }
            };
        }

        pub fn run(self: Self, ctx: *Context(Env)) Failure!A {
            const executor = ctx.executor orelse return ctx.runEffect(self.left);
            if (!executor.canRace()) return ctx.runEffect(self.left);

            const LJob = Job(Left);
            const RJob = Job(Right);
            var ls: Slot = .pending;
            var rs: Slot = .pending;
            var lj = LJob{ .ctx_value = ctx.*, .eff = self.left, .slot = &ls };
            var rj = RJob{ .ctx_value = ctx.*, .eff = self.right, .slot = &rs };

            const lh = executor.vtable.spawn(executor.context, .{ .context = &lj, .run = LJob.run }) orelse {
                LJob.run(&lj); // spawn declined — sequential
                return raceSlotResult(A, Failure, ls);
            };
            const rh = executor.vtable.spawn(executor.context, .{ .context = &rj, .run = RJob.run }) orelse {
                // right declined; drain left, return it
                executor.vtable.join(executor.context, lh);
                executor.vtable.destroy(executor.context, lh);
                return raceSlotResult(A, Failure, ls);
            };

            var handles = [_]*anyopaque{ lh, rh };
            const winner = executor.vtable.waitAny.?(executor.context, &handles);
            // Cancel the loser, then join + destroy both.
            _ = executor.tryInterrupt(handles[1 - winner]);
            executor.vtable.join(executor.context, lh);
            executor.vtable.destroy(executor.context, lh);
            executor.vtable.join(executor.context, rh);
            executor.vtable.destroy(executor.context, rh);

            return raceSlotResult(A, Failure, if (winner == 0) ls else rs);
        }

        pub fn exit(self: Self, ctx: *Context(Env)) Exit(A, Failure) {
            const value = ctx.runEffect(self) catch |err| return .{ .failure = err };
            return .{ .success = value };
        }
        pub fn map(self: Self, comptime Next: type, mapper: *const fn (A) Next) effect_mod.MapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .mapper = mapper };
        }
        pub fn flatMap(self: Self, comptime Next: type, binder: *const fn (A, *Context(Env)) Failure!Next) effect_mod.FlatMapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .binder = binder };
        }
    };
}

/// M4.5 — `raceAll(items)`: the first of N homogeneous effects to complete wins;
/// all losers are interrupted. Needs `ctx.allocator` for the spawn bookkeeping.
pub fn RaceAllEffect(
    comptime Item: type,
    comptime Failure: type,
    comptime Env: type,
) type {
    return struct {
        const Self = @This();
        const A = Item.SuccessType;
        pub const SuccessType = A;
        pub const FailureType = Failure;
        pub const EnvType = Env;

        items: []const Item,

        const Slot = union(enum) { pending, value: A, err: Failure };
        const Job = struct {
            ctx_value: Context(Env),
            eff: Item,
            slot: *Slot,
            fn run(raw: ?*anyopaque) void {
                const self: *Job = @ptrCast(@alignCast(raw.?));
                if (self.ctx_value.runEffect(self.eff)) |v| {
                    self.slot.* = .{ .value = v };
                } else |e| {
                    self.slot.* = .{ .err = e };
                }
            }
        };

        pub fn run(self: Self, ctx: *Context(Env)) Failure!A {
            std.debug.assert(self.items.len > 0);
            const executor = ctx.executor orelse return ctx.runEffect(self.items[0]);
            if (!executor.canRace()) return ctx.runEffect(self.items[0]);

            const slots = ctx.allocator.alloc(Slot, self.items.len) catch return @as(Failure, error.OutOfMemory);
            defer ctx.allocator.free(slots);
            for (slots) |*s| s.* = .pending;
            const jobs = ctx.allocator.alloc(Job, self.items.len) catch return @as(Failure, error.OutOfMemory);
            defer ctx.allocator.free(jobs);
            const handles = ctx.allocator.alloc(*anyopaque, self.items.len) catch return @as(Failure, error.OutOfMemory);
            defer ctx.allocator.free(handles);

            var spawned: usize = 0;
            for (self.items, 0..) |item, i| {
                jobs[i] = .{ .ctx_value = ctx.*, .eff = item, .slot = &slots[i] };
                if (executor.vtable.spawn(executor.context, .{ .context = &jobs[i], .run = Job.run })) |h| {
                    handles[i] = h;
                    spawned += 1;
                } else {
                    // spawn declined — drain what we have, run this one inline, return it.
                    for (handles[0..spawned]) |prior| {
                        executor.vtable.join(executor.context, prior);
                        executor.vtable.destroy(executor.context, prior);
                    }
                    Job.run(&jobs[i]);
                    return raceSlotResult(A, Failure, slots[i]);
                }
            }

            const winner = executor.vtable.waitAny.?(executor.context, handles);
            for (handles, 0..) |h, i| {
                if (i != winner) _ = executor.tryInterrupt(h);
            }
            for (handles) |h| {
                executor.vtable.join(executor.context, h);
                executor.vtable.destroy(executor.context, h);
            }
            return raceSlotResult(A, Failure, slots[winner]);
        }

        pub fn exit(self: Self, ctx: *Context(Env)) Exit(A, Failure) {
            const value = ctx.runEffect(self) catch |err| return .{ .failure = err };
            return .{ .success = value };
        }
        pub fn map(self: Self, comptime Next: type, mapper: *const fn (A) Next) effect_mod.MapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .mapper = mapper };
        }
        pub fn flatMap(self: Self, comptime Next: type, binder: *const fn (A, *Context(Env)) Failure!Next) effect_mod.FlatMapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .binder = binder };
        }
    };
}

/// M4.3 — `race(left, right)`: prefer SUCCESS. The first branch to complete
/// SUCCESSFULLY wins (the loser is interrupted); if the first completer FAILED,
/// the result is the other branch's outcome (we wait for it). Both branches
/// must produce the same Success type. Falls back to sequential when no racing
/// executor (run left; on failure, run right).
pub fn RaceEffect(
    comptime Left: type,
    comptime Right: type,
    comptime Failure: type,
    comptime Env: type,
) type {
    return struct {
        const Self = @This();
        const A = Left.SuccessType;
        pub const SuccessType = A;
        pub const FailureType = Failure;
        pub const EnvType = Env;

        left: Left,
        right: Right,

        const Slot = union(enum) { pending, value: A, err: Failure };

        fn Job(comptime Eff: type) type {
            return struct {
                ctx_value: Context(Env),
                eff: Eff,
                slot: *Slot,
                fn run(raw: ?*anyopaque) void {
                    const self: *@This() = @ptrCast(@alignCast(raw.?));
                    if (self.ctx_value.runEffect(self.eff)) |v| {
                        self.slot.* = .{ .value = v };
                    } else |e| {
                        self.slot.* = .{ .err = e };
                    }
                }
            };
        }

        pub fn run(self: Self, ctx: *Context(Env)) Failure!A {
            const executor = ctx.executor orelse return self.sequential(ctx);
            if (!executor.canRace()) return self.sequential(ctx);

            const LJob = Job(Left);
            const RJob = Job(Right);
            var ls: Slot = .pending;
            var rs: Slot = .pending;
            var lj = LJob{ .ctx_value = ctx.*, .eff = self.left, .slot = &ls };
            var rj = RJob{ .ctx_value = ctx.*, .eff = self.right, .slot = &rs };

            const lh = executor.vtable.spawn(executor.context, .{ .context = &lj, .run = LJob.run }) orelse {
                LJob.run(&lj);
                return raceSlotResult(A, Failure, ls);
            };
            const rh = executor.vtable.spawn(executor.context, .{ .context = &rj, .run = RJob.run }) orelse {
                executor.vtable.join(executor.context, lh);
                executor.vtable.destroy(executor.context, lh);
                return raceSlotResult(A, Failure, ls);
            };

            var handles = [_]*anyopaque{ lh, rh };
            const first = executor.vtable.waitAny.?(executor.context, &handles);
            const first_slot = if (first == 0) ls else rs;

            switch (first_slot) {
                .value => |v| {
                    // First to complete SUCCEEDED — it wins, interrupt the other.
                    _ = executor.tryInterrupt(handles[1 - first]);
                    joinDestroyBoth(executor, lh, rh);
                    return v;
                },
                .err => {
                    // First completer FAILED — the result is the other branch.
                    executor.vtable.join(executor.context, handles[1 - first]); // wait for it
                    const other_slot = if (first == 0) rs else ls;
                    joinDestroyBoth(executor, lh, rh);
                    return raceSlotResult(A, Failure, other_slot);
                },
                .pending => unreachable,
            }
        }

        fn sequential(self: Self, ctx: *Context(Env)) Failure!A {
            return ctx.runEffect(self.left) catch return ctx.runEffect(self.right);
        }

        pub fn exit(self: Self, ctx: *Context(Env)) Exit(A, Failure) {
            const value = ctx.runEffect(self) catch |err| return .{ .failure = err };
            return .{ .success = value };
        }
        pub fn map(self: Self, comptime Next: type, mapper: *const fn (A) Next) effect_mod.MapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .mapper = mapper };
        }
        pub fn flatMap(self: Self, comptime Next: type, binder: *const fn (A, *Context(Env)) Failure!Next) effect_mod.FlatMapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .binder = binder };
        }
    };
}

/// M4.6 — `both(left, right)`: parallel pair, FAIL-FAST. If either branch fails,
/// the other is interrupted and the failure returned; if both succeed, returns
/// the `ZipPair`. Distinct from `zipPar` (which waits for both regardless). Each
/// side may have its own Success type. Falls back to sequential `zip` semantics
/// when no racing executor.
pub fn BothEffect(
    comptime Left: type,
    comptime Right: type,
    comptime Failure: type,
    comptime Env: type,
) type {
    return struct {
        const Self = @This();
        pub const SuccessType = ZipPair(Left.SuccessType, Right.SuccessType);
        pub const FailureType = Failure;
        pub const EnvType = Env;

        left: Left,
        right: Right,

        const LeftSlot = union(enum) { pending, value: Left.SuccessType, err: Failure };
        const RightSlot = union(enum) { pending, value: Right.SuccessType, err: Failure };
        const LeftJob = struct {
            ctx_value: Context(Env),
            eff: Left,
            slot: *LeftSlot,
            fn run(raw: ?*anyopaque) void {
                const self: *@This() = @ptrCast(@alignCast(raw.?));
                if (self.ctx_value.runEffect(self.eff)) |v| {
                    self.slot.* = .{ .value = v };
                } else |e| {
                    self.slot.* = .{ .err = e };
                }
            }
        };
        const RightJob = struct {
            ctx_value: Context(Env),
            eff: Right,
            slot: *RightSlot,
            fn run(raw: ?*anyopaque) void {
                const self: *@This() = @ptrCast(@alignCast(raw.?));
                if (self.ctx_value.runEffect(self.eff)) |v| {
                    self.slot.* = .{ .value = v };
                } else |e| {
                    self.slot.* = .{ .err = e };
                }
            }
        };

        pub fn run(self: Self, ctx: *Context(Env)) Failure!SuccessType {
            const executor = ctx.executor orelse return self.sequential(ctx);
            if (!executor.canRace()) return self.sequential(ctx);

            var ls: LeftSlot = .pending;
            var rs: RightSlot = .pending;
            var lj = LeftJob{ .ctx_value = ctx.*, .eff = self.left, .slot = &ls };
            var rj = RightJob{ .ctx_value = ctx.*, .eff = self.right, .slot = &rs };

            const lh = executor.vtable.spawn(executor.context, .{ .context = &lj, .run = LeftJob.run }) orelse {
                LeftJob.run(&lj);
                RightJob.run(&rj);
                return assemble(ls, rs);
            };
            const rh = executor.vtable.spawn(executor.context, .{ .context = &rj, .run = RightJob.run }) orelse {
                executor.vtable.join(executor.context, lh);
                executor.vtable.destroy(executor.context, lh);
                RightJob.run(&rj);
                return assemble(ls, rs);
            };

            var handles = [_]*anyopaque{ lh, rh };
            const first = executor.vtable.waitAny.?(executor.context, &handles);
            const first_failed = if (first == 0) (ls == .err) else (rs == .err);

            if (first_failed) {
                // Fail-fast: interrupt the other branch.
                _ = executor.tryInterrupt(handles[1 - first]);
            } else {
                // First succeeded — wait for the other (it decides the outcome).
                executor.vtable.join(executor.context, handles[1 - first]);
            }
            joinDestroyBoth(executor, lh, rh);
            return assemble(ls, rs);
        }

        fn assemble(ls: LeftSlot, rs: RightSlot) Failure!SuccessType {
            // Any error wins (fail-fast). Check both sides regardless of order,
            // so the failing side's error is returned even when the other was
            // interrupted before completing (its slot stays .pending).
            switch (ls) {
                .err => |e| return e,
                else => {},
            }
            switch (rs) {
                .err => |e| return e,
                else => {},
            }
            // No errors → both succeeded (the join guarantees the other is set).
            return .{ .left = ls.value, .right = rs.value };
        }

        fn sequential(self: Self, ctx: *Context(Env)) Failure!SuccessType {
            const a = try ctx.runEffect(self.left);
            const b = try ctx.runEffect(self.right);
            return .{ .left = a, .right = b };
        }

        pub fn exit(self: Self, ctx: *Context(Env)) Exit(SuccessType, Failure) {
            const value = ctx.runEffect(self) catch |err| return .{ .failure = err };
            return .{ .success = value };
        }
        pub fn map(self: Self, comptime Next: type, mapper: *const fn (SuccessType) Next) effect_mod.MapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .mapper = mapper };
        }
        pub fn flatMap(self: Self, comptime Next: type, binder: *const fn (SuccessType, *Context(Env)) Failure!Next) effect_mod.FlatMapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .binder = binder };
        }
    };
}

fn joinDestroyBoth(executor: anytype, lh: *anyopaque, rh: *anyopaque) void {
    executor.vtable.join(executor.context, lh);
    executor.vtable.destroy(executor.context, lh);
    executor.vtable.join(executor.context, rh);
    executor.vtable.destroy(executor.context, rh);
}

/// Sequential traversal — apply `body(item, ctx)` to each input item,
/// collecting the per-item results into an allocated slice. Failure short-
/// circuits; the partial result slice is freed before the error returns.
/// `EnvType` is the effect environment the body runs against.
pub fn ForEachAllocEffect(
    comptime Item: type,
    comptime Result: type,
    comptime Failure: type,
    comptime Env: type,
) type {
    return struct {
        const Self = @This();
        pub const SuccessType = []Result;
        pub const FailureType = Failure;
        pub const EnvType = Env;

        items: []const Item,
        body: *const fn (Item, *Context(Env)) Failure!Result,

        pub fn run(self: Self, ctx: *Context(Env)) Failure!SuccessType {
            const results = ctx.allocator.alloc(Result, self.items.len) catch
                return @as(Failure, error.OutOfMemory);
            errdefer ctx.allocator.free(results);
            for (self.items, 0..) |item, i| {
                results[i] = try self.body(item, ctx);
            }
            return results;
        }

        pub fn exit(self: Self, ctx: *Context(Env)) Exit(SuccessType, Failure) {
            const value = ctx.runEffect(self) catch |err| return .{ .failure = err };
            return .{ .success = value };
        }

        pub fn map(
            self: Self,
            comptime Next: type,
            mapper: *const fn (SuccessType) Next,
        ) effect_mod.MapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .mapper = mapper };
        }

        pub fn flatMap(
            self: Self,
            comptime Next: type,
            binder: *const fn (SuccessType, *Context(Env)) Failure!Next,
        ) effect_mod.FlatMapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .binder = binder };
        }
    };
}

/// Sequential traversal that discards per-item results. Yields `void`.
/// Useful for "apply side-effecting body to each item; stop on first failure".
pub fn ForEachDiscardEffect(
    comptime Item: type,
    comptime Failure: type,
    comptime Env: type,
) type {
    return struct {
        const Self = @This();
        pub const SuccessType = void;
        pub const FailureType = Failure;
        pub const EnvType = Env;

        items: []const Item,
        body: *const fn (Item, *Context(Env)) Failure!void,

        pub fn run(self: Self, ctx: *Context(Env)) Failure!void {
            for (self.items) |item| try self.body(item, ctx);
        }

        pub fn exit(self: Self, ctx: *Context(Env)) Exit(void, Failure) {
            ctx.runEffect(self) catch |err| return .{ .failure = err };
            return .{ .success = {} };
        }

        pub fn map(
            self: Self,
            comptime Next: type,
            mapper: *const fn (void) Next,
        ) effect_mod.MapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .mapper = mapper };
        }

        pub fn flatMap(
            self: Self,
            comptime Next: type,
            binder: *const fn (void, *Context(Env)) Failure!Next,
        ) effect_mod.FlatMapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .binder = binder };
        }
    };
}

/// Sequential gather over a slice of homogeneous effects. Allocates a result
/// slice via `ctx.allocator`; caller owns and frees it. Failure short-circuits
/// — any results already collected are freed before returning the error.
pub fn AllEffect(
    comptime Item: type,
    comptime Failure: type,
    comptime Env: type,
) type {
    return struct {
        const Self = @This();
        pub const SuccessType = []Item.SuccessType;
        pub const FailureType = Failure;
        pub const EnvType = Env;

        items: []const Item,

        pub fn run(self: Self, ctx: *Context(Env)) Failure!SuccessType {
            const results = ctx.allocator.alloc(Item.SuccessType, self.items.len) catch
                return @as(Failure, error.OutOfMemory);
            errdefer ctx.allocator.free(results);
            for (self.items, 0..) |item, i| {
                results[i] = try ctx.runEffect(item);
            }
            return results;
        }

        pub fn exit(self: Self, ctx: *Context(Env)) Exit(SuccessType, Failure) {
            const value = ctx.runEffect(self) catch |err| return .{ .failure = err };
            return .{ .success = value };
        }

        pub fn map(
            self: Self,
            comptime Next: type,
            mapper: *const fn (SuccessType) Next,
        ) effect_mod.MapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .mapper = mapper };
        }

        pub fn flatMap(
            self: Self,
            comptime Next: type,
            binder: *const fn (SuccessType, *Context(Env)) Failure!Next,
        ) effect_mod.FlatMapEffect(Self, Next, Failure, Env) {
            return .{ .parent = self, .binder = binder };
        }
    };
}
